/**
 * GenFabTools Parking Engine - Excel Export Utility
 *
 * Professional Excel export for architectural feasibility studies.
 * Designed to be meeting-ready and client-presentable.
 */

import * as XLSX from "xlsx";
import type {
    Scenario,
    ParkingConfig,
    SurfaceMetrics,
    StructuredMetrics,
} from "../types";

// =============================================================================
// Types
// =============================================================================

interface ExportOptions {
    activeScenario: Scenario;
    allScenarios: readonly Scenario[];
}

// =============================================================================
// Formatting Helpers
// =============================================================================

function formatParkingType(type: string): string {
    return type === "surface" ? "Surface Lot" : "Parking Structure";
}

function formatAisleType(direction: string): string {
    return direction === "TWO_WAY" ? "Two-Way" : "One-Way";
}

function formatNumber(n: number): string {
    return n.toLocaleString("en-US", { maximumFractionDigits: 0 });
}

function formatDate(timestamp: string): string {
    return new Date(timestamp).toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
    });
}

function getSetbacksDescription(config: ParkingConfig): string {
    if (config.uniformSetback !== false) {
        return `${config.setback} ft (uniform)`;
    }
    const s = config.setbacks;
    if (!s) return `${config.setback} ft (uniform)`;
    return `N:${s.north} S:${s.south} E:${s.east} W:${s.west}`;
}

// =============================================================================
// Sheet 1: Executive Summary
// =============================================================================

function generateSummarySheet(scenario: Scenario): XLSX.WorkSheet {
    const result = scenario.result;
    const parkingResult = result?.parkingResult;
    const config = scenario.parkingConfig;

    const data: (string | number)[][] = [];

    // Title
    data.push(
        ["PARKING FEASIBILITY SUMMARY"],
        ["Generated by GenFabTools v2.0"],
        [],
        ["Scenario", scenario.name],
        ["Date", result ? formatDate(result.timestamp) : "—"],
        []
    );

    if (parkingResult?.type === "surface") {
        const m = parkingResult.metrics as SurfaceMetrics;

        // Configuration
        data.push(
            ["CONFIGURATION"],
            ["Type", formatParkingType(config.parkingType)],
            ["Aisles", `${formatAisleType(config.aisleDirection)} @ ${config.aisleDirection === "TWO_WAY" ? 24 : 12} ft`],
            []
        );

        // Results - the key metrics
        data.push(
            ["STALL COUNT"],
            ["Total Stalls", formatNumber(m.totalStalls)],
            ["   Standard", formatNumber(m.standardStalls)],
            ["   ADA Accessible", formatNumber(m.adaStalls)],
            []
        );

        // Efficiency
        data.push(
            ["EFFICIENCY"],
            ["Efficiency", `${m.efficiencySfPerStall.toFixed(0)} SF/stall`],
            ["Site Utilization", `${(m.usabilityRatio * 100).toFixed(0)}%`],
            []
        );

        // Areas
        data.push(
            ["AREAS"],
            ["Gross Site Area", `${formatNumber(m.totalArea)} SF`],
            ["Net Parkable Area", `${formatNumber(m.parkableArea)} SF`],
            ["Lost to Setbacks/Geometry", `${formatNumber(m.areaLostToGeometry)} SF (${m.areaLostToGeometryPct.toFixed(0)}%)`],
            []
        );

    } else if (parkingResult?.type === "structured") {
        const m = parkingResult.metrics as StructuredMetrics;

        // Configuration
        data.push(
            ["CONFIGURATION"],
            ["Type", formatParkingType(config.parkingType)],
            ["Levels", formatNumber(m.levelCount)],
            ["Height", `${m.totalHeight} ft`],
            []
        );

        // Results
        data.push(
            ["STALL COUNT"],
            ["Total Stalls", formatNumber(m.totalStalls)],
            ["Stalls per Level", m.stallsPerLevel.map(n => formatNumber(n)).join(" / ")],
            []
        );

        // Efficiency
        data.push(
            ["EFFICIENCY"],
            ["Efficiency", `${m.efficiencySfPerStall.toFixed(0)} SF/stall`],
            []
        );

        // Losses
        if (m.stallsLostToRamps > 0 || m.stallsLostToCores > 0 || m.stallsLostToConstraints > 0) {
            data.push(
                ["DEDUCTIONS"],
                ["Lost to Ramps", formatNumber(m.stallsLostToRamps)],
                ["Lost to Cores", formatNumber(m.stallsLostToCores)],
                ["Lost to Constraints", formatNumber(m.stallsLostToConstraints)],
                []
            );
        }
    } else {
        data.push(
            [],
            ["Results not available — run Evaluate to generate parking layout"]
        );
    }

    // Ruleset footer
    data.push(
        ["STANDARDS"],
        ["Code Basis", "IBC / ADA Accessibility Guidelines"],
        ["ADA Ratio", "Per IBC Table 1106.1"],
        ["Units", "Feet (ft) / Square Feet (SF)"]
    );

    const ws = XLSX.utils.aoa_to_sheet(data);
    ws["!cols"] = [{ wch: 28 }, { wch: 32 }];
    return ws;
}

// =============================================================================
// Sheet 2: Design Assumptions
// =============================================================================

function generateAssumptionsSheet(scenario: Scenario): XLSX.WorkSheet {
    const config = scenario.parkingConfig;
    const setbacks = config.setbacks || {
        north: config.setback,
        south: config.setback,
        east: config.setback,
        west: config.setback,
    };

    const data: (string | number)[][] = [];

    // Title
    data.push(
        ["DESIGN ASSUMPTIONS"],
        [],
    );

    // Stall Modules
    data.push(
        ["STALL MODULES"],
        ["Standard Stall", "9 ft × 18 ft"],
        ["ADA Accessible", "16 ft total (11 ft stall + 5 ft access aisle)"],
        ["Van-Accessible", "19 ft total (11 ft stall + 8 ft access aisle)"],
        []
    );

    // Aisle Configuration
    data.push(
        ["DRIVE AISLES"],
        ["Type", formatAisleType(config.aisleDirection)],
        ["Width", `${config.aisleDirection === "TWO_WAY" ? 24 : 12} ft`],
        []
    );

    // Setbacks
    data.push(["SETBACKS"]);
    if (config.uniformSetback !== false) {
        data.push(
            ["All Edges", `${config.setback} ft`],
            ["Mode", "Uniform"]
        );
    } else {
        data.push(
            ["North (Top)", `${setbacks.north} ft`],
            ["South (Bottom)", `${setbacks.south} ft`],
            ["East (Right)", `${setbacks.east} ft`],
            ["West (Left)", `${setbacks.west} ft`],
            ["Mode", "Per-edge (screen-based orientation)"]
        );
    }
    data.push([]);

    // Orientation note
    data.push(
        ["ORIENTATION"],
        ["Directions", "Screen-based (not geographic)"],
        ["North", "Top of drawing"]
    );

    // Structured parking specifics
    if (config.parkingType === "structured" && config.structuredConfig) {
        const sc = config.structuredConfig;
        data.push(
            [],
            ["STRUCTURE"],
            ["Levels", String(sc.levels)],
            ["Floor-to-Floor", `${sc.floorToFloorHeight} ft`],
            ["Ramp Type", sc.rampType],
            ["Ramp Location", sc.rampLocation],
            ["Core Location", sc.coreLocation]
        );
    }

    const ws = XLSX.utils.aoa_to_sheet(data);
    ws["!cols"] = [{ wch: 28 }, { wch: 40 }];
    return ws;
}

// =============================================================================
// Sheet 3: Scenario Comparison
// =============================================================================

function generateComparisonSheet(scenarios: readonly Scenario[]): XLSX.WorkSheet | null {
    const evaluated = scenarios.filter(s => s.result?.parkingResult);
    if (evaluated.length < 2) return null;

    const data: (string | number)[][] = [];

    // Title
    data.push(
        ["SCENARIO COMPARISON"],
        []
    );

    // Header row
    data.push(["", ...evaluated.map(s => s.name)]);

    // Key metrics
    data.push(
        ["Total Stalls", ...evaluated.map(s => s.result?.parkingResult.metrics.totalStalls ?? "—")],
        ["Efficiency (SF/stall)", ...evaluated.map(s => {
            const eff = s.result?.parkingResult.metrics.efficiencySfPerStall;
            return eff ? `${eff.toFixed(0)}` : "—";
        })]
    );

    // Surface-specific
    const hasSurface = evaluated.some(s => s.result?.parkingResult.type === "surface");
    if (hasSurface) {
        data.push(
            ["Standard Stalls", ...evaluated.map(s => {
                const r = s.result?.parkingResult;
                return r?.type === "surface" ? (r.metrics as SurfaceMetrics).standardStalls : "—";
            })],
            ["ADA Stalls", ...evaluated.map(s => {
                const r = s.result?.parkingResult;
                return r?.type === "surface" ? (r.metrics as SurfaceMetrics).adaStalls : "—";
            })],
            ["Site Utilization", ...evaluated.map(s => {
                const r = s.result?.parkingResult;
                return r?.type === "surface"
                    ? `${((r.metrics as SurfaceMetrics).usabilityRatio * 100).toFixed(0)}%`
                    : "—";
            })]
        );
    }

    // Structured-specific
    const hasStructured = evaluated.some(s => s.result?.parkingResult.type === "structured");
    if (hasStructured) {
        data.push(
            ["Levels", ...evaluated.map(s => {
                const r = s.result?.parkingResult;
                return r?.type === "structured" ? (r.metrics as StructuredMetrics).levelCount : "—";
            })],
            ["Structure Height", ...evaluated.map(s => {
                const r = s.result?.parkingResult;
                return r?.type === "structured" ? `${(r.metrics as StructuredMetrics).totalHeight} ft` : "—";
            })]
        );
    }

    // Configuration differences
    data.push(
        [],
        ["Configuration"],
        ["Parking Type", ...evaluated.map(s => formatParkingType(s.parkingConfig.parkingType))],
        ["Aisle Type", ...evaluated.map(s => formatAisleType(s.parkingConfig.aisleDirection))],
        ["Setbacks", ...evaluated.map(s => getSetbacksDescription(s.parkingConfig))]
    );

    const ws = XLSX.utils.aoa_to_sheet(data);
    ws["!cols"] = [{ wch: 20 }, ...evaluated.map(() => ({ wch: 18 }))];
    return ws;
}

// =============================================================================
// Main Export Function
// =============================================================================

export function exportToExcel(options: ExportOptions): void {
    const { activeScenario, allScenarios } = options;

    console.log("[ExcelExport] Generating professional parking study export v2.0");

    const wb = XLSX.utils.book_new();

    // Sheet 1: Executive Summary
    const summarySheet = generateSummarySheet(activeScenario);
    XLSX.utils.book_append_sheet(wb, summarySheet, "Summary");

    // Sheet 2: Design Assumptions
    const assumptionsSheet = generateAssumptionsSheet(activeScenario);
    XLSX.utils.book_append_sheet(wb, assumptionsSheet, "Assumptions");

    // Sheet 3: Scenario Comparison (if applicable)
    const comparisonSheet = generateComparisonSheet(allScenarios);
    if (comparisonSheet) {
        XLSX.utils.book_append_sheet(wb, comparisonSheet, "Comparison");
    }

    // Filename: Parking_Study_ScenarioName_YYYY-MM-DD.xlsx
    const safeName = activeScenario.name.replace(/[^a-zA-Z0-9]/g, "_");
    const dateStr = new Date().toISOString().split("T")[0];
    const filename = `Parking_Study_${safeName}_${dateStr}.xlsx`;

    XLSX.writeFile(wb, filename);
}

